package luars.entity;
// Generated Feb 15, 2012 9:15:19 AM by Hibernate Tools 3.2.1.GA



/**
 * Nas generated by hbm2java
 */
public class Nas  implements java.io.Serializable {


     private int timestamp;
     private Pings pings;
     private Double shipLat;
     private Double shipLng;
     private Double arrayCenterLat;
     private Double arrayCenterLng;
     private Double arrayHeading;
     private Double arrayDepth;
     private Double arrayTemperature;
     private Double arrayRoll;
     private Double arrayPitch;
     private Double arrayPressure;

    public Nas() {
    }

	
    public Nas(int timestamp) {
        this.timestamp = timestamp;
    }
    public Nas(int timestamp, Pings pings, Double shipLat, Double shipLng, Double arrayCenterLat, Double arrayCenterLng, Double arrayHeading, Double arrayDepth, Double arrayTemperature, Double arrayRoll, Double arrayPitch, Double arrayPressure) {
       this.timestamp = timestamp;
       this.pings = pings;
       this.shipLat = shipLat;
       this.shipLng = shipLng;
       this.arrayCenterLat = arrayCenterLat;
       this.arrayCenterLng = arrayCenterLng;
       this.arrayHeading = arrayHeading;
       this.arrayDepth = arrayDepth;
       this.arrayTemperature = arrayTemperature;
       this.arrayRoll = arrayRoll;
       this.arrayPitch = arrayPitch;
       this.arrayPressure = arrayPressure;
    }
   
    public int getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(int timestamp) {
        this.timestamp = timestamp;
    }
    public Pings getPings() {
        return this.pings;
    }
    
    public void setPings(Pings pings) {
        this.pings = pings;
    }
    public Double getShipLat() {
        return this.shipLat;
    }
    
    public void setShipLat(Double shipLat) {
        this.shipLat = shipLat;
    }
    public Double getShipLng() {
        return this.shipLng;
    }
    
    public void setShipLng(Double shipLng) {
        this.shipLng = shipLng;
    }
    public Double getArrayCenterLat() {
        return this.arrayCenterLat;
    }
    
    public void setArrayCenterLat(Double arrayCenterLat) {
        this.arrayCenterLat = arrayCenterLat;
    }
    public Double getArrayCenterLng() {
        return this.arrayCenterLng;
    }
    
    public void setArrayCenterLng(Double arrayCenterLng) {
        this.arrayCenterLng = arrayCenterLng;
    }
    public Double getArrayHeading() {
        return this.arrayHeading;
    }
    
    public void setArrayHeading(Double arrayHeading) {
        this.arrayHeading = arrayHeading;
    }
    public Double getArrayDepth() {
        return this.arrayDepth;
    }
    
    public void setArrayDepth(Double arrayDepth) {
        this.arrayDepth = arrayDepth;
    }
    public Double getArrayTemperature() {
        return this.arrayTemperature;
    }
    
    public void setArrayTemperature(Double arrayTemperature) {
        this.arrayTemperature = arrayTemperature;
    }
    public Double getArrayRoll() {
        return this.arrayRoll;
    }
    
    public void setArrayRoll(Double arrayRoll) {
        this.arrayRoll = arrayRoll;
    }
    public Double getArrayPitch() {
        return this.arrayPitch;
    }
    
    public void setArrayPitch(Double arrayPitch) {
        this.arrayPitch = arrayPitch;
    }
    public Double getArrayPressure() {
        return this.arrayPressure;
    }
    
    public void setArrayPressure(Double arrayPressure) {
        this.arrayPressure = arrayPressure;
    }




}


