package luars.entity;
// Generated Feb 15, 2012 9:15:19 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pings generated by hbm2java
 */
public class Pings  implements java.io.Serializable {


     private Integer pingId;
     private Tracks tracks;
     private Date startTime;
     private double duration;
     private double headingAvg;
     private double receiverLat;
     private double receiverLng;
     private double sourceLat;
     private double sourceLng;
     private double minEasting;
     private double maxEasting;
     private double minNorthing;
     private double maxNorthing;
     private Set nases = new HashSet(0);
     private Set sources = new HashSet(0);
     private Set whaleses = new HashSet(0);
     private Set pingsToSourceses = new HashSet(0);

    public Pings() {
    }

	
    public Pings(Tracks tracks, Date startTime, double duration, double headingAvg, double receiverLat, double receiverLng, double sourceLat, double sourceLng, double minEasting, double maxEasting, double minNorthing, double maxNorthing) {
        this.tracks = tracks;
        this.startTime = startTime;
        this.duration = duration;
        this.headingAvg = headingAvg;
        this.receiverLat = receiverLat;
        this.receiverLng = receiverLng;
        this.sourceLat = sourceLat;
        this.sourceLng = sourceLng;
        this.minEasting = minEasting;
        this.maxEasting = maxEasting;
        this.minNorthing = minNorthing;
        this.maxNorthing = maxNorthing;
    }
    public Pings(Tracks tracks, Date startTime, double duration, double headingAvg, double receiverLat, double receiverLng, double sourceLat, double sourceLng, double minEasting, double maxEasting, double minNorthing, double maxNorthing, Set sources, Set nases, Set whaleses, Set pingsToSourceses) {
       this.tracks = tracks;
       this.startTime = startTime;
       this.duration = duration;
       this.headingAvg = headingAvg;
       this.receiverLat = receiverLat;
       this.receiverLng = receiverLng;
       this.sourceLat = sourceLat;
       this.sourceLng = sourceLng;
       this.minEasting = minEasting;
       this.maxEasting = maxEasting;
       this.minNorthing = minNorthing;
       this.maxNorthing = maxNorthing;
       this.nases = nases;
       this.sources = sources;
       this.whaleses = whaleses;
       this.pingsToSourceses = pingsToSourceses;
    }
   
    public Integer getPingId() {
        return this.pingId;
    }
    
    public void setPingId(Integer pingId) {
        this.pingId = pingId;
    }
    public Tracks getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Tracks tracks) {
        this.tracks = tracks;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public double getDuration() {
        return this.duration;
    }
    
    public void setDuration(double duration) {
        this.duration = duration;
    }
    public double getHeadingAvg() {
        return this.headingAvg;
    }
    
    public void setHeadingAvg(double headingAvg) {
        this.headingAvg = headingAvg;
    }
    public double getReceiverLat() {
        return this.receiverLat;
    }
    
    public void setReceiverLat(double receiverLat) {
        this.receiverLat = receiverLat;
    }
    public double getReceiverLng() {
        return this.receiverLng;
    }
    
    public void setReceiverLng(double receiverLng) {
        this.receiverLng = receiverLng;
    }
    public double getSourceLat() {
        return this.sourceLat;
    }
    
    public void setSourceLat(double sourceLat) {
        this.sourceLat = sourceLat;
    }
    public double getSourceLng() {
        return this.sourceLng;
    }
    
    public void setSourceLng(double sourceLng) {
        this.sourceLng = sourceLng;
    }
    public double getMinEasting() {
        return this.minEasting;
    }
    
    public void setMinEasting(double minEasting) {
        this.minEasting = minEasting;
    }
    public double getMaxEasting() {
        return this.maxEasting;
    }
    
    public void setMaxEasting(double maxEasting) {
        this.maxEasting = maxEasting;
    }
    public double getMinNorthing() {
        return this.minNorthing;
    }
    
    public void setMinNorthing(double minNorthing) {
        this.minNorthing = minNorthing;
    }
    public double getMaxNorthing() {
        return this.maxNorthing;
    }
    
    public void setMaxNorthing(double maxNorthing) {
        this.maxNorthing = maxNorthing;
    }
    public Set getNases() {
        return this.nases;
    }
    
    public void setNases(Set nases) {
        this.nases = nases;
    }
    public Set getWhaleses() {
        return this.whaleses;
    }
    
    public void setWhaleses(Set whaleses) {
        this.whaleses = whaleses;
    }
    public Set getPingsToSourceses() {
        return this.pingsToSourceses;
    }
    
    public void setPingsToSourceses(Set pingsToSourceses) {
        this.pingsToSourceses = pingsToSourceses;
    }

    /**
     * @return the sources
     */
    public Set getSources() {
        return sources;
    }

    /**
     * @param sources the sources to set
     */
    public void setSources(Set sources) {
        this.sources = sources;
    }




}


