package luars.entity;
// Generated Feb 15, 2012 9:15:19 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Sources generated by hbm2java
 */
public class Sources  implements java.io.Serializable {


     private Integer sourceId;
     private String waveformName;
     private String filter;
     private BigDecimal startFreq;
     private BigDecimal stopFreq;
     private BigDecimal centerFreq;
     private BigDecimal bandwidth;
     private String tbetween;
     private Integer repitition;
     private String upDn;
     private BigDecimal pulseLength;
     private BigDecimal passLow;
     private BigDecimal passHigh;
     private BigDecimal transLow;
     private BigDecimal transHigh;
     private BigDecimal FShift;
     private Integer passBw;
     private BigDecimal totalBw;
     private BigDecimal maxDec;
     private BigDecimal minSr2;
     private Integer suggDec;
     private Integer suggSr2;
     private BigDecimal desCut;
     private BigDecimal desTrans;
     private String subAps;
     private Set pingsToSourceses = new HashSet(0);
     private Set pings = new HashSet(0);

    public Sources() {
    }

    public Sources(String waveformName, String filter, BigDecimal startFreq, BigDecimal stopFreq, BigDecimal centerFreq, BigDecimal bandwidth, String tbetween, Integer repitition, String upDn, BigDecimal pulseLength, BigDecimal passLow, BigDecimal passHigh, BigDecimal transLow, BigDecimal transHigh, BigDecimal FShift, Integer passBw, BigDecimal totalBw, BigDecimal maxDec, BigDecimal minSr2, Integer suggDec, Integer suggSr2, BigDecimal desCut, BigDecimal desTrans, String subAps, Set pingsToSourceses, Set pings) {
       this.waveformName = waveformName;
       this.filter = filter;
       this.startFreq = startFreq;
       this.stopFreq = stopFreq;
       this.centerFreq = centerFreq;
       this.bandwidth = bandwidth;
       this.tbetween = tbetween;
       this.repitition = repitition;
       this.upDn = upDn;
       this.pulseLength = pulseLength;
       this.passLow = passLow;
       this.passHigh = passHigh;
       this.transLow = transLow;
       this.transHigh = transHigh;
       this.FShift = FShift;
       this.passBw = passBw;
       this.totalBw = totalBw;
       this.maxDec = maxDec;
       this.minSr2 = minSr2;
       this.suggDec = suggDec;
       this.suggSr2 = suggSr2;
       this.desCut = desCut;
       this.desTrans = desTrans;
       this.subAps = subAps;
       this.pingsToSourceses = pingsToSourceses;
       this.pings = pings;
    }
   
    public Integer getSourceId() {
        return this.sourceId;
    }
    
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }
    public String getWaveformName() {
        return this.waveformName;
    }
    
    public void setWaveformName(String waveformName) {
        this.waveformName = waveformName;
    }
    public String getFilter() {
        return this.filter;
    }
    
    public void setFilter(String filter) {
        this.filter = filter;
    }
    public BigDecimal getStartFreq() {
        return this.startFreq;
    }
    
    public void setStartFreq(BigDecimal startFreq) {
        this.startFreq = startFreq;
    }
    public BigDecimal getStopFreq() {
        return this.stopFreq;
    }
    
    public void setStopFreq(BigDecimal stopFreq) {
        this.stopFreq = stopFreq;
    }
    public BigDecimal getCenterFreq() {
        return this.centerFreq;
    }
    
    public void setCenterFreq(BigDecimal centerFreq) {
        this.centerFreq = centerFreq;
    }
    public BigDecimal getBandwidth() {
        return this.bandwidth;
    }
    
    public void setBandwidth(BigDecimal bandwidth) {
        this.bandwidth = bandwidth;
    }
    public String getTbetween() {
        return this.tbetween;
    }
    
    public void setTbetween(String tbetween) {
        this.tbetween = tbetween;
    }
    public Integer getRepitition() {
        return this.repitition;
    }
    
    public void setRepitition(Integer repitition) {
        this.repitition = repitition;
    }
    public String getUpDn() {
        return this.upDn;
    }
    
    public void setUpDn(String upDn) {
        this.upDn = upDn;
    }
    public BigDecimal getPulseLength() {
        return this.pulseLength;
    }
    
    public void setPulseLength(BigDecimal pulseLength) {
        this.pulseLength = pulseLength;
    }
    public BigDecimal getPassLow() {
        return this.passLow;
    }
    
    public void setPassLow(BigDecimal passLow) {
        this.passLow = passLow;
    }
    public BigDecimal getPassHigh() {
        return this.passHigh;
    }
    
    public void setPassHigh(BigDecimal passHigh) {
        this.passHigh = passHigh;
    }
    public BigDecimal getTransLow() {
        return this.transLow;
    }
    
    public void setTransLow(BigDecimal transLow) {
        this.transLow = transLow;
    }
    public BigDecimal getTransHigh() {
        return this.transHigh;
    }
    
    public void setTransHigh(BigDecimal transHigh) {
        this.transHigh = transHigh;
    }
    public BigDecimal getFShift() {
        return this.FShift;
    }
    
    public void setFShift(BigDecimal FShift) {
        this.FShift = FShift;
    }
    public Integer getPassBw() {
        return this.passBw;
    }
    
    public void setPassBw(Integer passBw) {
        this.passBw = passBw;
    }
    public BigDecimal getTotalBw() {
        return this.totalBw;
    }
    
    public void setTotalBw(BigDecimal totalBw) {
        this.totalBw = totalBw;
    }
    public BigDecimal getMaxDec() {
        return this.maxDec;
    }
    
    public void setMaxDec(BigDecimal maxDec) {
        this.maxDec = maxDec;
    }
    public BigDecimal getMinSr2() {
        return this.minSr2;
    }
    
    public void setMinSr2(BigDecimal minSr2) {
        this.minSr2 = minSr2;
    }
    public Integer getSuggDec() {
        return this.suggDec;
    }
    
    public void setSuggDec(Integer suggDec) {
        this.suggDec = suggDec;
    }
    public Integer getSuggSr2() {
        return this.suggSr2;
    }
    
    public void setSuggSr2(Integer suggSr2) {
        this.suggSr2 = suggSr2;
    }
    public BigDecimal getDesCut() {
        return this.desCut;
    }
    
    public void setDesCut(BigDecimal desCut) {
        this.desCut = desCut;
    }
    public BigDecimal getDesTrans() {
        return this.desTrans;
    }
    
    public void setDesTrans(BigDecimal desTrans) {
        this.desTrans = desTrans;
    }
    public String getSubAps() {
        return this.subAps;
    }
    
    public void setSubAps(String subAps) {
        this.subAps = subAps;
    }
    public Set getPingsToSourceses() {
        return this.pingsToSourceses;
    }
    
    public void setPingsToSourceses(Set pingsToSourceses) {
        this.pingsToSourceses = pingsToSourceses;
    }

    /**
     * @return the pings
     */
    public Set getPings() {
        return pings;
    }

    /**
     * @param pings the pings to set
     */
    public void setPings(Set pings) {
        this.pings = pings;
    }




}


