package luars.entity;
// Generated Feb 15, 2012 9:15:19 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tracks generated by hbm2java
 */
public class Tracks  implements java.io.Serializable {


     private Integer trackId;
     private String name;
     private String dataDir;
     private Set pingses = new HashSet(0);

    public Tracks() {
    }

	
    public Tracks(String name, String dataDir) {
        this.name = name;
        this.dataDir = dataDir;
    }
    public Tracks(String name, String dataDir, Set pingses) {
       this.name = name;
       this.dataDir = dataDir;
       this.pingses = pingses;
    }
   
    public Integer getTrackId() {
        return this.trackId;
    }
    
    public void setTrackId(Integer trackId) {
        this.trackId = trackId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDataDir() {
        return this.dataDir;
    }
    
    public void setDataDir(String dataDir) {
        this.dataDir = dataDir;
    }
    public Set getPingses() {
        return this.pingses;
    }
    
    public void setPingses(Set pingses) {
        this.pingses = pingses;
    }




}


