package luars.entity;
// Generated Feb 15, 2012 9:15:19 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Whales generated by hbm2java
 */
public class Whales implements java.io.Serializable {

    private Integer whaleId;
    private WhaleGroups whaleGroups;
    private Pings pings;
    private Date datetime;
    private Double timeStart;
    private Double timeStop;
    private Double freqStart;
    private Double freqCenter;
    private Double freqStop;
    private Double soundPressureLevel;
    private Double relativeBeamMusic;
    private Double relativeBeamCdsb;
    private Double trueBearing;
    private Double arrayHeading;
    private Double arrayLat;
    private Double arrayLng;
    private boolean timeBoundsAccurate;
    private boolean freqBoundsAccurate;
    private boolean movieCreated;
    private boolean audioCreated;
    private Date lastUpdated;
    private Double f0MLE;
    private Double f1MLE;
    private Double timeStartMLE;
    private Double durationMLE;

    public Whales() {
    }

    public Whales(Pings pings, boolean timeBoundsAccurate, boolean freqBoundsAccurate, boolean movieCreated, boolean audioCreated) {
        this.pings = pings;
        this.timeBoundsAccurate = timeBoundsAccurate;
        this.freqBoundsAccurate = freqBoundsAccurate;
        this.movieCreated = movieCreated;
        this.audioCreated = audioCreated;
    }

    public Whales(WhaleGroups whaleGroups, Pings pings, Date datetime, Double timeStart, Double timeStop, Double freqStart, Double freqStop, Double soundPressureLevel, Double relativeBeamMusic, Double relativeBeamCdsb, Double trueBearing, boolean timeBoundsAccurate, boolean freqBoundsAccurate, boolean movieCreated, boolean audioCreated, Date lastUpdated) {
        this.whaleGroups = whaleGroups;
        this.pings = pings;
        this.datetime = datetime;
        this.timeStart = timeStart;
        this.timeStop = timeStop;
        this.freqStart = freqStart;
        this.freqStop = freqStop;
        this.soundPressureLevel = soundPressureLevel;
        this.relativeBeamMusic = relativeBeamMusic;
        this.relativeBeamCdsb = relativeBeamCdsb;
        this.trueBearing = trueBearing;
        this.timeBoundsAccurate = timeBoundsAccurate;
        this.freqBoundsAccurate = freqBoundsAccurate;
        this.movieCreated = movieCreated;
        this.audioCreated = audioCreated;
        this.lastUpdated = lastUpdated;
    }

    public Integer getWhaleId() {
        return this.whaleId;
    }

    public void setWhaleId(Integer whaleId) {
        this.whaleId = whaleId;
    }

    public WhaleGroups getWhaleGroups() {
        return this.whaleGroups;
    }

    public void setWhaleGroups(WhaleGroups whaleGroups) {
        this.whaleGroups = whaleGroups;
    }

    public Pings getPings() {
        return this.pings;
    }

    public void setPings(Pings pings) {
        this.pings = pings;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public Double getTimeStart() {
        return this.timeStart;
    }

    public void setTimeStart(Double timeStart) {
        this.timeStart = timeStart;
    }

    public Double getTimeStop() {
        return this.timeStop;
    }

    public void setTimeStop(Double timeStop) {
        this.timeStop = timeStop;
    }

    public Double getFreqStart() {
        return this.freqStart;
    }

    public void setFreqStart(Double freqStart) {
        this.freqStart = freqStart;
    }

    public Double getFreqCenter() {
        return this.freqCenter;
    }

    public void setFreqCenter(Double freqCenter) {
        this.freqCenter = freqCenter;
    }

    public Double getFreqStop() {
        return this.freqStop;
    }

    public void setFreqStop(Double freqStop) {
        this.freqStop = freqStop;
    }
    
    public Double getF0MLE() {
        return this.f0MLE;
    }

    public void setF0MLE(Double f0MLE) {
        this.f0MLE = f0MLE;
    }
    
    public Double getF1MLE() {
        return this.f1MLE;
    }

    public void setF1MLE(Double f1MLE) {
        this.f1MLE = f1MLE;
    }
    
    public Double getTimeStartMLE() {
        return this.timeStartMLE;
    }

    public void setTimeStartMLE(Double timeStartMLE) {
        this.timeStartMLE = timeStartMLE;
    }
    
    public Double getDurationMLE() {
        return this.durationMLE;
    }

    public void setDurationMLE(Double durationMLE) {
        this.durationMLE = durationMLE;
    }

    public Double getSoundPressureLevel() {
        return this.soundPressureLevel;
    }

    public void setSoundPressureLevel(Double soundPressureLevel) {
        this.soundPressureLevel = soundPressureLevel;
    }

    public Double getRelativeBeamMusic() {
        return this.relativeBeamMusic;
    }

    public void setRelativeBeamMusic(Double relativeBeamMusic) {
        this.relativeBeamMusic = relativeBeamMusic;
    }

    public Double getRelativeBeamCdsb() {
        return this.relativeBeamCdsb;
    }

    public void setRelativeBeamCdsb(Double relativeBeamCdsb) {
        this.relativeBeamCdsb = relativeBeamCdsb;
    }

    public Double getTrueBearing() {
        return this.trueBearing;
    }

    public void setTrueBearing(Double trueBearing) {
        this.trueBearing = trueBearing;
    }

    public boolean isTimeBoundsAccurate() {
        return this.timeBoundsAccurate;
    }

    public void setTimeBoundsAccurate(boolean timeBoundsAccurate) {
        this.timeBoundsAccurate = timeBoundsAccurate;
    }

    public boolean isFreqBoundsAccurate() {
        return this.freqBoundsAccurate;
    }

    public void setFreqBoundsAccurate(boolean freqBoundsAccurate) {
        this.freqBoundsAccurate = freqBoundsAccurate;
    }

    public boolean isMovieCreated() {
        return this.movieCreated;
    }

    public void setMovieCreated(boolean movieCreated) {
        this.movieCreated = movieCreated;
    }

    public boolean isAudioCreated() {
        return this.audioCreated;
    }

    public void setAudioCreated(boolean audioCreated) {
        this.audioCreated = audioCreated;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * @return the arrayHeading
     */
    public Double getArrayHeading() {
        return arrayHeading;
    }

    /**
     * @param arrayHeading the arrayHeading to set
     */
    public void setArrayHeading(Double arrayHeading) {
        this.arrayHeading = arrayHeading;
    }

    /**
     * @return the arrayLat
     */
    public Double getArrayLat() {
        return arrayLat;
    }

    /**
     * @param arrayLat the arrayLat to set
     */
    public void setArrayLat(Double arrayLat) {
        this.arrayLat = arrayLat;
    }

    /**
     * @return the arrayLng
     */
    public Double getArrayLng() {
        return arrayLng;
    }

    /**
     * @param arrayLng the arrayLng to set
     */
    public void setArrayLng(Double arrayLng) {
        this.arrayLng = arrayLng;
    }
}
